version: '3.7'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOSTNAME: localhost
      KAFKA_ZOOKER_CONNECT: zookeeper:2181

  laravel:
    build: 
      context: ./src/app
      dockerfile: dockerfile
    container_name: laravel
    restart: unless-stopped
    working_dir: /var/www/app
    depends_on:
        - mysql
        - kafka
    volumes:
        - ./src/app:/var/www/app
    networks:
        - assessment
      
  mysql:
    image: bitnami/mysql:8.0.20
    container_name: mysql
    restart: unless-stopped
    ports:
        - 3306:3306
    environment:
        ALLOW_EMPTY_PASSWORD: yes
        MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    volumes:
        - ./mysql:/bitnami/mysql/data
    networks:
        - assessment

  nginx:
    depends_on:
      - laravel
    build: 
      context: ./nginx
      dockerfile: dockerfile
    ports:
      - "9000:90"
    volumes:
      - ./src:/var/www
    networks:
      - assessment
      
networks:
  assessment:
    driver: bridge