# Pull the minimal Ubuntu image
FROM ubuntu

# Install Nginx
RUN apt-get -y update && apt-get -y install nginx
RUN apt-get -y update && apt-get -y install sudo
RUN sudo apt-get install policycoreutils -y
RUN apt-get -y update && apt-get -y install net-tools

# Copy the Nginx config
COPY default.conf /etc/nginx/default.conf

# Run the Nginx server
CMD ["/usr/sbin/nginx", "-g", "daemon off;"]